version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 10
    reviewers:
      - 'm3au'
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'
    groups:
      dev-dependencies:
        patterns:
          - '@*/*'
          - 'eslint*'
          - 'typescript*'
          - 'playwright*'
          - 'axe*'
          - 'lighthouse*'
          - 'husky*'
          - 'lint*'
          - 'markdownlint*'
          - 'cspell*'
        update-types:
          - 'minor'
          - 'patch'
      production-dependencies:
        patterns:
          - '*'
        exclude-patterns:
          - '@*/*'
          - 'eslint*'
          - 'typescript*'
          - 'playwright*'
          - 'axe*'
          - 'lighthouse*'
          - 'husky*'
          - 'lint*'
          - 'markdownlint*'
          - 'cspell*'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: 'bun'
        update-types:
          [
            'version-update:semver-major',
            'version-update:semver-minor',
            'version-update:semver-patch',
          ]
      - dependency-name: 'node'
        update-types:
          [
            'version-update:semver-major',
            'version-update:semver-minor',
            'version-update:semver-patch',
          ]
